config {
    type: "table",
    schema: "transformed_data",
    name: "orders",
    assertions: {
        uniqueKey: ["order_id"],
        nonNull: ["user_id", "status", "order_date", "num_of_item"]
    }
}

SELECT 
    order_id,
    user_id,
    status, 
    Date(created_at) as order_date,
    Date(returned_at) as returned_date,
    Date(shipped_at) as shipped_date,
    Date(delivered_at) as delivered_date,
    num_of_item
FROM 
    `source_data.orders`
