config {
    type: "table",
    schema: "transformed_data",
    name: "products",
    assertions: {
        uniqueKey: ["id"],
        nonNull: ["cost", "category", "name", "brand", "retail_price", "department", "distribution_center_id"]
    }
} 
SELECT 
    id as product_id,
    cost,
    category,
    name,
    brand,
    retail_price,
    department,
    distribution_center_id
FROM `source_data.products`