config {
    type: "table",
    schema: "transformed_data",  
    name: "users", 
    assertions: { 
        uniqueKey: ["user_id"],  
        nonNull: ["first_name", "country", "signup_date"],  
        rowConditions: [
            'age < 100',  
            'gender IN ("M", "F")'
        ]
    }
}

SELECT 
    id as user_id,
    first_name,
    email,
    age,
    gender,
    country,
    Date(created_at) as signup_date
FROM 
    `source_data.users`